language: node_js

node_js:
  - "8"
  - "node"

sudo: false

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - yarn run lint
  - yarn run test

after_success: 'yarn run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
